# pull official base image
FROM node:16-alpine

WORKDIR /usr/src

# ENV PATH /usr/src/node_modules/.bin:$PATH
# ENV PATH /usr/src/ecsite/node_modules/.bin:$PATH

ENV HOST 0.0.0.0
EXPOSE 8080

# install dependencies
# RUN npm install -g @vue/cli