# Generated by Django 3.2.12 on 2022-03-23 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.CharField(blank=True, choices=[('01', 'PC・周辺機器'), ('02', 'オフィス用品'), ('03', '家電')], max_length=2, null=True, verbose_name='大分類'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_subcategory',
            field=models.CharField(blank=True, choices=[('01', 'ノートパソコン'), ('02', 'デスクトップパソコン'), ('03', 'ディスプレイ'), ('04', 'ノート'), ('05', '手帳'), ('06', '筆記用具'), ('07', '電子レンジ'), ('08', '冷蔵庫'), ('09', 'エアコン')], max_length=2, null=True, verbose_name='小分類'),
        ),
    ]
