# Generated by Django 3.2.12 on 2022-04-05 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20220323_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='商品画像'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.CharField(blank=True, choices=[('01', 'PC・周辺機器'), ('02', 'オフィス用品'), ('03', '家電')], max_length=2, null=True, verbose_name='分類'),
        ),
    ]
